# Install server
- hosts: puppet_server
  become: yes
  roles:
    - puppet_server

- hosts: puppet_agent
  become: yes
  roles:
    - puppet_agent

- hosts: puppet_db
  become: yes
  roles:
    - puppet_db

