---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Puppet Agent
  apt:
    name: puppet-agent
    state: present

- name: Start and enable Puppet Agent service
  systemd:
    name: puppet
    enabled: yes
    state: started